import { z } from "zod";
import { Types } from "mongoose";

const ObjectIdSchema = z.string().refine((val) => Types.ObjectId.isValid(val), {
  message: "Invalid ObjectId",
});

const bookItemSchema = z.object({
  book: ObjectIdSchema,
  bookTitle: z.string().min(1, "Title required"),
  productImage: z.string().url("Invalid image URL"),
  seller: ObjectIdSchema,
  price: z.number().positive(), // unit price; line total = price * quantity
  quantity: z.number().int().positive(),
});

// ─────────────────────────────────────────────────────────────
// Checkout payload — this is what the controller receives from
// the frontend cart. NOTE: shippingCost is intentionally NOT
// accepted from the client here. Shipping is charged per seller
// shipment and must be computed server-side from shippingArea
// after the cart is split by seller (see order.service.ts) —
// otherwise a multi-seller cart would only ever be charged once
// for shipping even though it ships as N separate parcels.
// totalAmount is likewise recomputed server-side per resulting
// order, never trusted from the client.
// ─────────────────────────────────────────────────────────────

const createOrderSchema = z.object({
  books: z.array(bookItemSchema).min(1, "Cart cannot be empty"),
  buyer: ObjectIdSchema,
  phoneNumber: z.string().min(11, "Valid BD phone number required"),
  email: z.string().email("Invalid email address"),
  deliveryAddress: z.string().min(5, "Full address is required"),
  shippingArea: z.enum(["inside", "outside"], {
    errorMap: () => ({ message: "Select either Inside or Outside Chattogram" }),
  }),
  paymentMethod: z.enum(["cod", "bkash"], {
    errorMap: () => ({ message: "Select a valid payment method" }),
  }),
  // Optional for COD; checked against paymentMethod below.
  transactionId: z.string().optional(),
  comment: z.string().optional(),
}).refine((data) => {
  if (data.paymentMethod === "bkash") {
    // Reject missing AND reject the model's own "N/A" placeholder —
    // a real bKash order must carry a real transaction id, never
    // the default sentinel value that COD orders fall back to.
    return !!data.transactionId && data.transactionId.trim() !== "" && data.transactionId !== "N/A";
  }
  return true;
}, {
  message: "A valid Transaction ID is required for bKash payments",
  path: ["transactionId"],
});

// ─────────────────────────────────────────────────────────────
// Internal schema — validates ONE already-split, already-priced
// order document right before insertion. orderId, shippingCost,
// and totalAmount are server-generated by this point, so they're
// required here (unlike createOrderSchema, where they don't exist
// yet in the raw client payload).
// ─────────────────────────────────────────────────────────────

const internalOrderDocumentSchema = z.object({
  orderId: z.string().min(1),
  books: z.array(bookItemSchema).min(1),
  buyer: ObjectIdSchema,
  phoneNumber: z.string().min(11),
  email: z.string().email(),
  deliveryAddress: z.string().min(5),
  shippingArea: z.enum(["inside", "outside"]),
  shippingCost: z.number().nonnegative(),
  totalAmount: z.number().positive(),
  paymentMethod: z.enum(["cod", "bkash"]),
  transactionId: z.string(),
  comment: z.string().optional(),
});

const updateOrderSchema = z.object({
  // PATCH semantics: every field optional. A request that updates
  // only `orderStatus`, for example, must not be rejected for
  // missing `phoneNumber`/`deliveryAddress` — they weren't part of
  // the previous (non-optional) version of this schema, which
  // would have made every partial update fail validation.
  phoneNumber: z.string().min(11, "Valid BD phone number required").optional(),
  deliveryAddress: z.string().min(5, "Full address is required").optional(),
  comment: z.string().optional(),
  paymentStatus: z.enum(["pending", "paid", "partially-paid", "failed"]).optional(),
  orderStatus: z.enum(["pending", "confirmed", "shipped", "delivered", "cancelled"]).optional(),
}).refine((data) => Object.keys(data).length > 0, {
  message: "At least one field must be provided to update",
});

export const orderValidations = {
  createOrderSchema,
  internalOrderDocumentSchema,
  updateOrderSchema,
};